config/routes.rb
Rails.application.routes.draw do
  get 'page/home'

  get 'page/about'

  get 'page/contact'

  devise_for :users
  get 'home', :to => 'users#home'
  put 'users/:id' => 'users#update'

   root 'page#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
before_action :authenticate_user!

  def home
    
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
skip_before_filter :verify_authenticity_token  
  def home
    @users = User.all
  end
  def update
    #console.log(params[:user])
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      render json: @user.to_json, status: :ok
    end
  end
  private 
    def user_params
      params.require(:user).permit(:email, :id, :updated_at, :created_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Userapp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script>
      var myApp = angular.module('myApp',['Services']);
      myApp.controller('ngCtrl',['$scope','User',function($scope, User){
        $scope.init = function(){
          $scope.users = $("#data").data("users")
          console.log("huynh")
          //console.log($scope.users)
        };

        $scope.edit = function(user) {
        //  alert(user.email);
        
          $scope.user = {}
          angular.copy( user, $scope.user);

          $scope.save = function(params){
            console.log(params)
           // User.update(user: user)
            if (params.id != null) {
              User.update({
                user: params
              }).$promise.then((function(value) {
                console.log(value)
                angular.copy( value, user);
                angular.copy( value, $scope.user); 
               //$scope.hero = angular.copy(hero);
                return;
              }), function(error) {
                $scope.errors = error.data;
                $scope.success = null;
                return;
              });
              return;
            }
          };

        };

      }]);
  </script>
</head>
<body ng-app="myApp">
  <% if user_signed_in? %>
  
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %><br>

  <% else %>
  
  <%= link_to "Sign in", new_user_session_path %><br>
  <%= link_to "Sign up", new_user_registration_path %><br>

  <% end %>
  <%= link_to "Home", page_home_path %>
  <%= link_to "About", page_about_path %>
  <%= link_to "Contact", page_contact_path %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

<input ng-model="text1">
{{text1}}
</div>

app/views/users/_modal.html.erb
<div class="modal fade" id ="heroModal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <input ng-model="user.email"></input>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" ng-click=save(user)>Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/users/home.html.erb
<span id="data" data-users="<%= @users.to_json %>">
<div ng-controller="ngCtrl" ng-init="init()">
<h1>User Home</h1>

<table>
<%# @users.each do |user| %>
<tr ng-repeat="user in users">
  <td>{{user.email}}</td>
  <td><button ng-click="edit(user)">Edit</button></td>
  <td><button type="button" data-toggle="modal" data-target="#heroModal" ng-click="edit(user)">編集</button></td>
</tr>
<%# end %>
</table>
<%= render partial: "modal" %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>